backend:
  name: git-gateway
  repo: "dagr81ktl/liferstudiosblog"
  branch: main  # Название основной ветки репозитория
  debug: true

media_folder: "static/images/uploads" # Путь для загрузки изображений
public_folder: "/images/uploads"      # Путь для отображения изображений в URL

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    index: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}